cu:
  repository: 276594885557.dkr.ecr.ap-southeast-2.amazonaws.com/ran-simulator-cu
  tag: latest

du:
  repository: 276594885557.dkr.ecr.ap-southeast-2.amazonaws.com/ran-simulator-du
  tag: latest

pipeline:
  runId: manual
