cu:
  repository: 276594885557.dkr.ecr.ap-southeast-2.amazonaws.com/ran-simulator-cu
  tag: latest
  resources:
    requests:
      cpu: "400m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "256Mi"

du:
  repository: 276594885557.dkr.ecr.ap-southeast-2.amazonaws.com/ran-simulator-du
  tag: latest
  resources:
    requests:
      cpu: "400m"
      memory: "128Mi"
    limits:
      cpu: "1500m"
      memory: "256Mi"

pipeline:
  runId: manual

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 98

serviceMonitor:
  enabled: true

grafanaIngress:
  enabled: true
  ingressClassName: alb
  scheme: internet-facing
  targetType: ip
  healthcheckPath: /login
  successCodes: "200,302"

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3
