alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 24h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    rendering:
      server_url: http://grafana-image-renderer.monitoring.svc.cluster.local:8081/render
      callback_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local

  service:
    type: ClusterIP

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring

kube-state-metrics:
  metricLabelsAllowlist:
    - horizontalpodautoscalers=[app,pipeline_run_id,app_version]
    - pods=[app,pipeline_run_id,app_version]