apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu
  template:
    metadata:
      labels:
        app: cu
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: cu
          image: "{{ .Values.cu.repository }}:{{ .Values.cu.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: PIPELINE_RUN_ID
              value: "{{ .Values.pipeline.runId }}"
            - name: APP_VERSION
              value: "{{ .Values.cu.tag }}"
