{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ran-sim-monitor-cu
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cu
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}