{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: du-hpa
  labels:
    app: du
    pipeline_run_id: "{{ .Values.pipeline.runId }}"
    app_version: "{{ .Values.du.tag }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: du-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{- end }}
