{{- if .Values.grafanaIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: grafana-ingress
  namespace: monitoring

  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.grafanaIngress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.grafanaIngress.targetType }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.grafanaIngress.healthcheckPath }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.grafanaIngress.successCodes | quote }}

spec:
  ingressClassName: {{ .Values.grafanaIngress.ingressClassName }}

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
{{- end }}